os:
  - osx
  - linux

language: rust
sudo: required

rust:
  # - nightly
  # - beta
  - stable

before_install:
  - |
    ### Target dependent setup

    # OSX
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update
       brew uninstall libjpeg libpng libtiff --ignore-dependencies || true
       brew install openal-soft libsndfile
    fi

    # Linux
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get update
        sudo apt-get install -y libopenal-dev libsndfile1-dev
    fi

script:
  - cargo build
